plug:
  network_id: challenge.FreeMoney
  max_block_size: 1000
  registry:
    plugins:
    - free_money.FreeMoneyPlugin
  storage:
    class: plug.storage.sqlite.SqliteStorage
    path: db.sqlite
    store_n_states: 10
