plug:
  network_id: balance.tutorial
  max_block_size: 1000
  registry:
    plugins:
    - balance_tutorial.BalanceTutorialPlugin
  indexers:
    _state:
    - balance_tutorial.indexer.BalanceIndexer
  storage:
    class: plug.storage.sqlite.SqliteStorage
    path: db.sqlite
    store_n_states: 10
