plug:
  network_id: challenge.FreeMoney
  max_block_size: 1000
  registry:
    plugins:
    - free_money_challenge.FreeMoneyPlugin
  indexers:
    _state:
    - free_money_challenge.indexer.BalanceIndexer
  storage:
    class: plug.storage.sqlite.SqliteStorage
    path: db.sqlite
    store_n_states: 10
